sudo: false
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
notifications:
  email: false
script:
  - yarn lint
  - yarn test
after_script:
  - yarn release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
