sudo: false
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - yarn global add semantic-release
script:
  - yarn test
after_script:
  - semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
